### ISSUE TITLE
how about the accuracy of the calibrate code result?

### ISSUE THREAD

**Issue by tiexuedanxin** [REXJJ/rgbd-camera-calibration#24]
hello, I have calibrate my rgbd seneor with opencv stereocalibrate, and use the calibrate result to colorful the point cloud, but at the edge of the interest boject have some color of the background. how about the accuracy of the calibrate code result?

**Comment by REXJJ** [comment]
Hi, At present, this package only calculates the extrinsic parameter of the camera to a robot base. Methods for calculating intrinsic parameters and colour-depth extrinsic parameters are yet to be added.
